<!DOCTYPE html>
<html>
<head>
<title>first web</title>
</head>
<body>
<h1>HELLO EVERYONE</h1>
<p>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<br>bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb<br>cccccccccccccccccccccccccccccccccccccccccccccccc<br></p>
<p>this is my first <b>attemt</b></p>
<p<i>you can be make like this</i>></p>
<body>
<h1>paragraph 1</h1>
<p><mark>learn html</mark></p>
<p><small>learn html</small></p>
<p><del>learn yyyyyyyyyyyyyhtml</del></p>
<p><b>learn html</b></p>
<p><i>learn html</i></p>
<p>learn & <ins>cloud</ins>html</p>
<p>(a+b)<sup>2</sup>=a<sup>2</sup>+2ab+b<sup>2</sup></p>
<p>H<sub>2</sub>O</p>
<p>you can be <strong>make</strong> like this</p>
color: aqua;
background-color: black;
olor: white;
background-color: brown;
<table style="width: 100%;"
    border="2">
    <caption>hamsakkante petti pedia</caption>
    <tr>
<th>sn</th>
<th>item</th>
<th>unit</th>
<th>quantdity</th>
</tr>
<tr>
<td>1</td>
<td>apple</td>
<td>kg</thd>
<td>100$</td>
  </tr>
tr>
<td>2</td>
<td>pen</td>
<td>nos</td>
<td>10$</td>
  </tr>
tr>
<td>3</td>
<td>pencil</td>
<td>nos</th>
<td>8$</td>
  </tr>
</table>

<table style="width: 100%;"
   border="2">
  <th>name</th>
<th colspan="3">contact</th>

<tr>
<td>3</td>
<td>pencil</td>
<td>nos</th>
  </tr>

</table>

table{
    border: 1px solid rgb(255, 0, 0);
border-collapse:collapse ;
background-color: rosybrown;
}

th,td{
    text-align: center;
    padding: 10px;

th{
    background-color: yellowgreen;
    color: white;
}


caption{
    font-size: xx-large;
    font-weight: bolder;
}
</body>
</html>